### ISSUE TITLE
Nothing happens on Signin button click.

### ISSUE THREAD

**Issue by harshivvp** [ShyykoSerhiy/vscode-spotify#82]
Hello, I'm using vscode on Ubuntu 18.04 and I've installed vscode-spotify(v3.1.0). 

When I try to click on the sign in button after having the spotify's desktop app up and running. I get an error in the dev tools's console. I'm guessing I'm supposed to be redirected but nothing happened as such.! When I checked for the open ports on ubuntu : 

code      13123            root   50u  IPv4 202770      0t0  TCP 127.0.0.1:36831 (LISTEN)
code      13123            root   84u  IPv6 202801      0t0  TCP *:8350 (LISTEN)

Can you help me out here. Thanks muchly.!

Devtools Console error : 

mainThreadExtensionService.ts:42 [shyykoserhiy.vscode-spotify]listen EADDRINUSE :::8350
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:42
t._doInvokeHandler @ rpcProtocol.ts:461
t._invokeHandler @ rpcProtocol.ts:446
t._receiveRequest @ rpcProtocol.ts:366
t._receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:171
e.fire @ event.ts:228
a @ ipc.net.ts:103
n._socketDataListener @ ipc.net.ts:132
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
mainThreadExtensionService.ts:43 Error: listen EADDRINUSE :::8350
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at Server.setupListenHandle [as _listen2] (net.js:1351:14)
	at listenInCluster (net.js:1392:12)
	at Server.listen (net.js:1476:7)
	at Function.listen (/root/.vscode/extensions/shyykoserhiy.vscode-spotify-3.1.0/node_modules/express/lib/application.js:618:24)
	at exports.createDisposableAuthSever.Promise (/root/.vscode/extensions/shyykoserhiy.vscode-spotify-3.1.0/out/src/auth/server/local.js:25:26)
	at new Promise (<anonymous>)
	at Object.exports.createDisposableAuthSever (/root/.vscode/extensions/shyykoserhiy.vscode-spotify-3.1.0/out/src/auth/server/local.js:8:33)
	at __dirname.actionSignIn.vscode_1.commands.executeCommand.then (/root/.vscode/extensions/shyykoserhiy.vscode-spotify-3.1.0/out/src/actions/actions.js:210:62)
	at <anonymous>

**Comment by audstanley** [comment]
It looks like your Ubuntu machine has binded to Port 8350, and has yet to release the port.  It is likely that you are currently running some service on it or that whatever was running on that port crashed.  Good news is that you should be able to still use play/pause next, previous commands. In the meantime, can you run and paste here?:

sudo lsof -i -P -n | grep 8350;

This should show you what service is running on that port.

**Comment by harshivvp** [comment]
I checked already for port 8350 being in use. Before i open vscode, nothing's bound to port 8350. And after I click on Spotify's Sign in button on vscode. It shows me "code 13123 root 84u IPv6 202801 0t0 TCP *:8350 (LISTEN)" which i already posted above. 

Weirdly enough sign in works normally on my other PC.
